import { EditorView } from "@codemirror/view";

export const editorTheme = EditorView.theme({
  "&": { height: "100%", fontSize: "13px" },
  ".cm-scroller": { overflow: "auto", fontFamily: "'Cascadia Code', Consolas, monospace" },
  ".cm-content": { padding: "18px 0", caretColor: "#c25c32" },
  ".cm-gutters": { backgroundColor: "#f4f6f2", border: "none", color: "#8b958a" },
  ".cm-activeLineGutter": { backgroundColor: "#e9eee8", color: "#293d31" },
  ".cm-activeLine": { backgroundColor: "#f7f8f5" },
  "&.cm-focused": { outline: "none" },
  ".cm-cursor": { borderLeftColor: "#c25c32" },
  ".cm-selectionBackground, ::selection": { backgroundColor: "#d8e3d5 !important" },
  // 搜尋面板：浮動在編輯器右上角（VS Code 風格），不佔用文字區高度。
  ".cm-panels": { position: "absolute", top: "0", right: "18px", left: "auto", width: "420px", maxWidth: "calc(100% - 26px)", background: "transparent !important", border: "none !important", color: "inherit", pointerEvents: "none", zIndex: "300" },
  ".cm-panels-top": { border: "none !important" },
  ".cm-vsc-search": { pointerEvents: "auto", display: "flex", alignItems: "flex-start", gap: "2px", width: "100%", padding: "6px 8px 6px 3px", border: "1px solid #dce2da", borderTop: "none", borderRadius: "0 0 5px 5px", background: "#f8faf6", boxShadow: "0 3px 10px rgba(38, 53, 45, 0.16)", color: "#26352d", fontFamily: "'Segoe UI Variable', 'Segoe UI', sans-serif", fontSize: "12px" },
  ".cm-vsc-search button": { font: "inherit" },
  ".cm-vsc-rows": { display: "flex", flex: "1", flexDirection: "column", gap: "4px", minWidth: "0" },
  ".cm-vsc-row": { display: "flex", alignItems: "center", gap: "2px" },
  ".cm-vsc-search:not(.replace-open) .cm-vsc-replace-row": { display: "none" },
  ".cm-vsc-field": { position: "relative", flex: "1", minWidth: "0" },
  ".cm-vsc-input": { width: "100%", height: "24px", padding: "0 6px", border: "1px solid #dce2da", borderRadius: "3px", background: "#fff", color: "inherit", font: "inherit", outline: "none" },
  ".cm-vsc-input:focus": { borderColor: "#6f8f73" },
  ".cm-vsc-find-input": { paddingRight: "74px" },
  ".cm-vsc-field.no-match .cm-vsc-input": { borderColor: "#ae5c3e" },
  ".cm-vsc-options": { position: "absolute", top: "0", right: "2px", bottom: "0", display: "flex", alignItems: "center", gap: "1px" },
  ".cm-vsc-option, .cm-vsc-icon-btn, .cm-vsc-toggle-replace": { display: "inline-flex", flex: "0 0 auto", alignItems: "center", justifyContent: "center", padding: "0", border: "1px solid transparent", borderRadius: "3px", background: "transparent", color: "#55665b", cursor: "pointer" },
  ".cm-vsc-option": { width: "22px", height: "20px", fontFamily: "'Cascadia Code', Consolas, monospace", fontSize: "11px" },
  ".cm-vsc-icon-btn": { width: "24px", height: "24px" },
  ".cm-vsc-toggle-replace": { alignSelf: "stretch", width: "16px" },
  ".cm-vsc-toggle-replace svg": { transition: "transform 0.12s" },
  ".cm-vsc-search.replace-open .cm-vsc-toggle-replace svg": { transform: "rotate(90deg)" },
  ".cm-vsc-option:hover, .cm-vsc-icon-btn:hover, .cm-vsc-toggle-replace:hover": { background: "#e9eee8" },
  ".cm-vsc-option.active": { borderColor: "#9db59f", background: "#d8e3d5", color: "#26352d" },
  ".cm-vsc-search button:focus-visible": { outline: "1px solid #6f8f73", outlineOffset: "-1px" },
  ".cm-vsc-count": { minWidth: "58px", padding: "0 4px", color: "#5e6f64", fontSize: "11px", textAlign: "center", whiteSpace: "nowrap" },
  ".cm-vsc-text-btn": { height: "24px", padding: "0 8px", border: "1px solid #dce2da", borderRadius: "3px", background: "#fff", color: "#34443a", cursor: "pointer", whiteSpace: "nowrap" },
  ".cm-vsc-text-btn:hover": { background: "#e9eee8" }
});
